language: php

php:
  - 7.3
  
before_script:
  # both instances are on the same machine
  - echo "Setting up environment"
  - echo "$PRIVATE_KEY_INSTANCE" > ~/pipeline-infra_kp64.pem
  - cat ~/pipeline-infra_kp64.pem | base64 -d > ~/pipeline-infra.pem
  - echo "$CONFIG_FILE" |base64 -d > ~/ssh.pipeline-infra.config
  - chmod 400 ~/pipeline-infra.pem

jobs:
  include:
    - stage: deploy
      if: branch = integration
      script:
      - echo 'Initializing Deploy into integration branch'
      - ssh -F ~/ssh.pipeline-infra.config $IP_INSTANCE "cd /var/www/iprueba_cicd_travis && sudo git pull origin integration && exit"
    
after_script:
  - echo 'Deploy has Finished"
