language: php

php:
  - 7.3
  
before_script:
  # both instnaces are on the same machine
  - echo "Setting up environment"
  - echo "$PRIVATE_KEY_INSTANCE" > ~/pipeline-infra_kp64.pem
  - cat ~/pipeline-infra_kp64.pem | base64 -d > ~/pipeline-infra.pem
  - echo "$CONFIG_FILE" |base64 -d > ~/ssh.pipeline-infra.config
  - chmod 400 ~/pipeline-infra.pem

jobs:
  include:
    - stage: deploy-int
      script:
      - echo 'Initializing Deploy into integration branch'
      - ssh -F ~/ssh.pipeline-infra.config $IP_INSTANCE "ls -l /var/www/iprueba_cicd_travis && exit"
      only:
        - integration
    - stage: deploy-pro
      script:
      - ssh -F ~/ssh.pipeline-infra.config $IP_INSTANCE "ls -l /var/www/pprueba_cicd_travis && exit"
      only:
        - master
stages:
  - name: deploy-int
    if: type = pull_request
  - name: deploy-pro
    if: type = push AND branch = master  
    
after_script:
  - echo 'Deploy has Finished"
