before_script:
  # both instnaces are on the same machine
  - echo "Setting up environment"
  - echo "PRIVATE_KEY_INSTANCE" >> ~/pipeline-infra_kp64.pem
  - cat ~/pipeline-infra_kp64.pem | base64 -d > ~/pipeline-infra.pem
   
jobs:
  include:
  - stage: deploy
    if: branch = develop
    script: 
    - echo 'Initializing Deploy into develop branch'
    - ssh  -i  ~/pipeline-infra.pem ubuntu@$IP_INSTANCE "ls -l /var/www && exit"

after_script:
  - echo 'Deploy has Finished