language: php

php:
  - 7.3
  
before_script:
  # both instnaces are on the same machine
  - echo "Setting up environment"
  - echo "$PRIVATE_KEY_INSTANCE" > ~/pipeline-infra_kp64.pem
  - cat ~/pipeline-infra_kp64.pem | base64 -d > ~/pipeline-infra.pem
  - echo "$CONFIG_FILE" |base64 -d > ~/ssh.pipeline-infra.config
  - chmod 400 ~/pipeline-infra.pem

deploy_develop:
  type: deploy
  environment:
    name: integration
  script:
    - echo 'Initializing Deploy into integration branch'
    - ssh -F ~/ssh.pipeline-infra.config $IP_INSTANCE "ls -l /var/www/iprueba_cicd_travis && exit"
only:
  - integration

deploy_master:
  type: deploy
  environment:
    name: master
  script:
    - ssh -F ~/ssh.pipeline-infra.config $IP_INSTANCE "ls -l /var/www/pprueba_cicd_travis && exit"
only:
  - master
after_script:
  - echo 'Deploy has Finished"
